services:
    telegabber:
        image: docker.io/galenguyer/telegabber:latest
        container_name: telegabber
        ports:
            - "5222:5222"
            - "5223:5223"
            - "5269:5269"
            - "8855:80"
        environment:
            TELEGRAM_API_ID: ${API_ID}
            TELEGRAM_API_HASH: ${API_HASH}
            MAIN_HOST: ${MAIN_HOST}
            LINK_HOST: ${LINK_HOST}
            FILES_HOST: ${FILES_HOST}
            TZ: "America/Denver"
        volumes:
            - "telegabber-data:/var/lib/prosody"
            - "telegabber-sessions:/sessions"

volumes:
    telegabber-data:
    telegabber-sessions:
